dist: bionic
python:
  - "3.7"

install:
  - |
    sudo apt-get update && sudo apt-get install -y virtualenv python3-virtualenv python3-pip
    virtualenv -p python3 venv
    source venv/bin/activate
    pip install -r requirements.txt

script:
  - source venv/bin/activate && pytest --version
